apiVersion: apps/v1
kind: Deployment
metadata:
  name: abs-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: abs-app
  template:
    metadata:
      labels:
        app: abs-app
    spec:
      initContainers:
      - name: migrate
        image: balaji93bobby/abs-app:${DOCKER_IMAGE_TAG}
        command: ['sh', '-c', 'php artisan config:clear']
        env:
        - name: DB_HOST
          value: mysql-service
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_PASSWORD
      containers:
      - name: abs-app
        image: balaji93bobby/abs-app:${DOCKER_IMAGE_TAG}
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: mysql-service
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_PASSWORD
