apiVersion: v1
kind: Service
metadata:
  name: abs-service
spec:
  selector:
    app: abs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
  type: NodePort
