<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithStrictNullComparison;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithHeadings;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;
use PhpOffice\PhpSpreadsheet\Style\Style;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithCustomStartCell;
use Maatwebsite\Excel\Concerns\WithDrawings;
use Carbon\Carbon;
use PhpOffice\PhpSpreadsheet\Style\Alignment;

class PMSFormSampleExcelExport implements WithStrictNullComparison, WithHeadings, ShouldAutoSize, WithCustomStartCell, WithStyles
{
    /**
     * @return \Illuminate\Support\Collection
     */

    private $headers;
    protected $client_name;
    protected $frequency;
    protected $assignment;
    protected $public_client_logo_path;
    protected $last_header_column;
    protected $last_row;
    protected $assignment_date;


    public function __construct($headers, $client_name, $frequency, $assignment,  $assignment_date, $public_client_logo_path,)
    {
        $this->headers = $headers;
        $this->client_name = $client_name;
        $this->frequency = $frequency;
        $this->assignment = $assignment;
        $this->assignment_date = $assignment_date;
        $this->public_client_logo_path = $public_client_logo_path;
        $this->last_header_column = num2alpha(count($headers) - 1);
        $this->last_row = 22;
    }
    public function startCell(): string
    {
        return 'A1';
    }
    public function headings(): array
    {
        return $this->headers;
    }
    public function styles(Worksheet $sheet)
    {
        $sheet->getParent()->getActiveSheet()->getPageSetup()->setpaperSize(1);
        $sheet->getParent()->getActiveSheet()->getPageSetup()->setOrientation(\PhpOffice\PhpSpreadsheet\Worksheet\PageSetup::ORIENTATION_LANDSCAPE);
        $sheet->getParent()->getActiveSheet()->getPageSetup()->setPaperSize(\PhpOffice\PhpSpreadsheet\Worksheet\PageSetup::PAPERSIZE_A3);

        ///$sheet->getParent()->getActiveSheet()->getProtection()->setSheet(true);


        //For Remove Grid Lines
      //  $sheet->setShowGridlines(false);

        // $sheet->mergeCells('D1:H1')->setCellValue('D1', "Legal Entity : " . $this->client_name);
        // $sheet->getStyle('D1:H1')->getFont()->setBold(true);
        // $sheet->getStyle('D1:H1')->getAlignment()->setVertical(Alignment::VERTICAL_CENTER);
        // $sheet->getStyle('D1:H1')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
        
        // //For Second Row
        // $sheet->mergeCells('D2:H2')->setCellValue('D2', "Frequency  : " . $this->frequency);
        // $sheet->getStyle('D2:H2')->getFont()->setBold(true);
        // $sheet->getStyle('D2:H2')->getAlignment()->setVertical(Alignment::VERTICAL_CENTER);
        // $sheet->getStyle('D2:H2')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

        // //For Third Row
        // $sheet->mergeCells('D3:H3')->setCellValue('D3', "Assignment Period : " . $this->assignment);
        // $sheet->getStyle('D3:H3')->getFont()->setBold(true);
        // $sheet->getStyle('D3:H3')->getAlignment()->setVertical(Alignment::VERTICAL_CENTER);
        // $sheet->getStyle('D3:H3')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
        //for fourth row
        // $sheet->mergeCells('C4:E4')->setCellValue('C4', $this->assignment_date);
        // $sheet->getStyle('C4:E4')->getFont()->setBold(true);

        $sheet->getStyle('A1:' . $this->last_header_column . '1')->getFill()
            ->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)
            ->getStartColor()->setRGB('002164');
        $sheet->getStyle('A1:' . $this->last_header_column . '1')->getFont()->setBold(true)
            ->getColor()->setRGB('ffffff');
        //for allignment
    //    $sheet->getStyle('A1:Z5')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);
    //    $sheet->getStyle('A1:Z5')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
      //  $range = 'A1:' . $this->last_header_column . $this->last_row - 1;
        // $sheet->getStyle('C1:E1')->getFont()->setBold(true);
        // $style = [
        //     'alignment' => [
        //         'horizontal' => \PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER,
        //         'vertical' => \PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER,
        //         'wrapText' => true,
        //     ],
        // ];

        // $sheet->mergeCells('A' . $this->last_row . ':G' . $this->last_row)->setCellValue('A' . $this->last_row, " This report is generated by ABShrms OKR Software : " . Carbon::now()->format('d-M-Y'));
        // $sheet->getStyle('A' . $this->last_row . ':G' . $this->last_row)->getFont()->setBold(true);
    }
    // public function drawings()
    // {
    //     $drawing = new Drawing();
    //     $drawing->setPath($this->public_client_logo_path);
    //     $drawing->setHeight(1200);
    //     $drawing->setWidth(224);
    //     $drawing->setCoordinates('A1');
    //     // $drawing->setOffsetX(100);
    //      $drawing->setOffsetY(100);
    //     return $drawing;
    // }
}
