<?php

namespace App\Exports;

use App\Models\VmtPMS_KPIFormReviewsModel;
use App\Models\User;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\FromArray;
use Carbon\Carbon;
use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;
use Maatwebsite\Excel\Concerns\WithColumnWidths;
use Maatwebsite\Excel\Concerns\WithStyles;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use Maatwebsite\Excel\Concerns\WithCustomStartCell;
use Maatwebsite\Excel\Events\AfterSheet;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Sheet;
use Maatwebsite\Excel\Concerns\FromQuery;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Style;
use PhpOffice\PhpSpreadsheet\Style\Color;
use PhpOffice\PhpSpreadsheet\Style\Border;


class VmtPmsReviewsReport implements ShouldAutoSize,FromArray,WithCustomStartCell,WithHeadings,WithStyles
{
    /**
     * @return \Illuminate\Support\Collection
     */

     protected $array_headings;
     protected $array_value;
     protected $last_header_column;
     protected $public_client_logo_path;
     protected $client_name;


    function __construct($array_headings,$array_value,$public_client_logo_path,$client_name)
    {
        $this->array_headings = $array_headings;
        $this->array_value = $array_value;
        $this->last_header_column = num2alpha(count($array_headings) - 1);
        $this->public_client_logo_path = $public_client_logo_path;
        $this->client_name = $client_name;
    }


    //For Headings
    public function headings(): array
    {
        return[
        $this->array_headings
        ];
    }


    public function startCell(): string
    {
        return 'A7';
    }

    public function array() : array
    {
        return $this->array_value;
    }

    public function styles(Worksheet $sheet){

            // second header
        $sheet->getStyle('A7:' . $this->last_header_column . '7')->getFont()->setBold(true);
        $sheet->getStyle('A7:' . $this->last_header_column . '7')->getFill()
            ->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)
            ->getStartColor()->setRGB('002164');
        $sheet->getStyle('A7:' . $this->last_header_column . '7')
            ->getFont()->setBold(true)->getColor()->setRGB('ffffff');

            //
            $sheet->mergeCells('A'.count($this->array_value) + 9 .':G'.count($this->array_value) + 9)->setCellValue('A'.count($this->array_value) + 9, " This report is generated by ABShrms Payroll Software : ".Carbon::now()->format('d-M-Y'));
            $sheet->getStyle('A'.count($this->array_value) + 9 .':G'.count($this->array_value) + 9)->getFont()->setBold(true);

            $sheet->setShowGridlines(false);

            $sheet->mergeCells('C1:E1')->setCellValue('C1', "Legal Entity : " . $this->client_name);
            $sheet->getStyle('C1:E1')->getFont()->setBold(true);

            //For Second Row
            $sheet->mergeCells('C2:E2')->setCellValue('C2', "Report Type : " .' Pms Report');
            $sheet->getStyle('C2:E2')->getFont()->setBold(true);
    }

    public function drawings()
    {
        $drawing = new Drawing();
        $drawing->setPath($this->public_client_logo_path);
        $drawing->setHeight(1200);
        $drawing->setWidth(224);
        $drawing->setCoordinates('A1');
        return $drawing;
    }

}
